# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Neurodesk
author: Neurodesk Team
logo: images/neurodesk_logo.svg
only_build_toc_files: true
# Logo created via https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tAZwBcAnCAa0xRBIEMp8AHG4zKQkAXwBoQaAPOPjwgExOABMAwhAA2EYlVr0mLNp24hxNQjWEBXYjKoALQoQb5kAeithxUAHQArfOMwy4aYg6iZCVqAYAWys0TAQaAFotHXw-fAABAEYrGJorIIgMTHxnfGhOHiDmMioAI2YQHlZIcTgoJFRwWXlheHdxKgBJAFkAEQAhAH0AJW16pB4y+uFivmn6FCSABg0ZcNZO5Cg9GRkefDAadeFiOgRKZABtEABiGDKwZYAmTp57x5e3u+WAZhoAJwwAAsVR+-yBoPewJgYF+MAA7GDbjC4YjkWVfpgAKywjFY3FgEAAXR4LDCxDiKBIekwHA0fGEhAAngxLiAAI56OiEOA6XlhMELWb8BZCZDPVY8doyLYgXqDUbjBpg-iCFA7PYHI4nJrkzCUy40ukaZlM1nsrk8vnjQU8GgIUThbTsyB6NT2gTizUyek8YyYRCmJbY5Y8AAkhwDxRMZgs1lCzocCD5xj0ZQccAgVijmGKiYikQ8hEwoWBDgAHA4knkChwgA

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true
  timeout: 86400
  stderr_output: error
  run_in_temp: true
  nb_merge_streams:  True
  execution_show_tb: True

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  binderhub_url: "https://play-ashburn.neurodesk.org/v2/gh/neurodesk/example-notebooks/main?labpath=/home/jovyan/examples/example-notebooks/books"

# Information about where the book exists on the web
repository:
  url: https://github.com/NeuroDesk/example-notebooks # Online location of your book
  path_to_book: books
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/neurodesk_logo.svg"
  baseurl: https://neurodesk.github.io/example-notebooks/intro.html
  repository_url: https://github.com/neurodesk/example-notebooks
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: G-4Z9774J59Y

sphinx:
  config:
    nb_execution_show_tb: True